spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pokedex-back-end
    username: pokedex
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        Type: TRACE
      springframework:
        security: DEBUG
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000
